// Auto-generated by LibreLane
module ai_byte_top(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk,
  input rst_n,
  input[3:0] addr,
  inout[7:0] data,
  input we,
  input re,
  output irq,
  output done_o,
  output error_o,
  output[2:0] debug_state
);
endmodule
