###############################################################################
# Created by write_sdc
###############################################################################
current_design ai_byte_top
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 110.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {addr[0]}]
set_input_delay 22.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {addr[0]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {addr[1]}]
set_input_delay 22.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {addr[1]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {addr[2]}]
set_input_delay 22.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {addr[2]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {addr[3]}]
set_input_delay 22.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {addr[3]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {data[0]}]
set_input_delay 22.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {data[0]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {data[1]}]
set_input_delay 22.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {data[1]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {data[2]}]
set_input_delay 22.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {data[2]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {data[3]}]
set_input_delay 22.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {data[3]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {data[4]}]
set_input_delay 22.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {data[4]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {data[5]}]
set_input_delay 22.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {data[5]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {data[6]}]
set_input_delay 22.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {data[6]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {data[7]}]
set_input_delay 22.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {data[7]}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {re}]
set_input_delay 22.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {re}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {rst_n}]
set_input_delay 22.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {rst_n}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -min -add_delay [get_ports {we}]
set_input_delay 22.0000 -clock [get_clocks {clk}] -max -add_delay [get_ports {we}]
set_output_delay 22.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data[0]}]
set_output_delay 22.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data[1]}]
set_output_delay 22.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data[2]}]
set_output_delay 22.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data[3]}]
set_output_delay 22.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data[4]}]
set_output_delay 22.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data[5]}]
set_output_delay 22.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data[6]}]
set_output_delay 22.0000 -clock [get_clocks {clk}] -add_delay [get_ports {data[7]}]
set_output_delay 22.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_state[0]}]
set_output_delay 22.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_state[1]}]
set_output_delay 22.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_state[2]}]
set_output_delay 22.0000 -clock [get_clocks {clk}] -add_delay [get_ports {done_o}]
set_output_delay 22.0000 -clock [get_clocks {clk}] -add_delay [get_ports {error_o}]
set_output_delay 22.0000 -clock [get_clocks {clk}] -add_delay [get_ports {irq}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0729 [get_ports {done_o}]
set_load -pin_load 0.0729 [get_ports {error_o}]
set_load -pin_load 0.0729 [get_ports {irq}]
set_load -pin_load 0.0729 [get_ports {data[7]}]
set_load -pin_load 0.0729 [get_ports {data[6]}]
set_load -pin_load 0.0729 [get_ports {data[5]}]
set_load -pin_load 0.0729 [get_ports {data[4]}]
set_load -pin_load 0.0729 [get_ports {data[3]}]
set_load -pin_load 0.0729 [get_ports {data[2]}]
set_load -pin_load 0.0729 [get_ports {data[1]}]
set_load -pin_load 0.0729 [get_ports {data[0]}]
set_load -pin_load 0.0729 [get_ports {debug_state[2]}]
set_load -pin_load 0.0729 [get_ports {debug_state[1]}]
set_load -pin_load 0.0729 [get_ports {debug_state[0]}]
###############################################################################
# Design Rules
###############################################################################
set_max_transition 3.0000 [current_design]
set_max_capacitance 0.2000 [current_design]
set_max_fanout 10.0000 [current_design]
